Update LexiTranslatable.php
Fix for the error caused when using the transAttr method on an untranslated field with a null value for $originalText.

Error: App\Models\Example::translate(): Return value must be of type string, null returned